# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [19]:
# Your code goes here
class Book:
    def __init__(self, title, author, pages, price):
        self.title = title
        self.author = author
        self.pages = pages
        self.set_price(price)
    # Method to return price.
    def get_price(self):
        return self.__price
    # Ensure price is numeric.
    def set_price(self, price):
        if not isinstance(price, (int, float)):
            raise TypeError("Price must be numeric")
        self.__price = price

In [20]:
# Create two instances of the class
b1 = Book("Practical Programming", "Gries, Campbell, Montojo", 383, 50)
b2 = Book("Building a Career in Data Science", "Robinson, Nolis", 322, 40)

#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [21]:
# Your code goes here
class Phone:
    def __init__(self, model, id, name, brand, price):
        self.set_model(model)
        self.set_id(id)
        self.set_name(name)
        self.set_brand(brand)
        self.set_price(price)

    # Getter for each attribute.
    def get_model(self):
        return self.__model
    def get_id(self):
        return self.__id
    def get_name(self):
        return self.__name
    def get_brand(self):
        return self.__brand
    def get_price(self):
        return self.__price

    # Setters for each attribute
    def set_model(self, model):
        self.__model = model
    def set_id(self, id):
        self.__id = id
    def set_name(self, name):
        self.__name = name
    def set_brand(self, brand):
        self.__brand = brand
    def set_price(self, price):
        self.__price = price

    # Method to calculate total price including tax.
    def calculate_total(self, tax):
        return self.__price * (1 + tax)

## Numpy

In [2]:
import numpy as np

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [23]:
# Your code goes here
arr = np.array([0,1,2,3,4,5])
reshaped = arr.reshape(2, 3)

reshaped

array([[0, 1, 2],
       [3, 4, 5]])

#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [24]:
# Your code goes here
bool_array = np.ones((3, 3), dtype=bool)
bool_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 3. Create a 1D array filled with zeros and another filled with ones

In [16]:
array_one = np.zeros(5)
array_two = np.ones(5)

In [17]:
# Check:
array_one.ndim

1

In [18]:
array_two.ndim

1

#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [25]:
# Your code goes here
arr = np.array([9,8,7,6,5,4,3,2,1,0])
reversed_arr = arr[::-1]
reversed_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [27]:
# Your code goes here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.hstack((a, b))
stacked

array([1, 2, 3, 4, 5, 6])

#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [29]:
# Your code goes here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
a+b

array([5, 7, 9])

In [30]:
# Multiplication
a*b

array([ 4, 10, 18])